import { isAxiosError } from "axios";
import { Metadata } from "next";

import { SingleDataPage } from "@/container/SingleDataPage";
import { Container } from "@/components/Container";
import { ApartmentDto } from "@/types/dto";
import { axios } from "@/services/axios";

type Props = {
  params: Promise<{ id: string }>;
};

export const generateMetadata = async ({
  params,
}: Props): Promise<Metadata> => {
  const id = (await params).id;

  try {
    const { data } = await axios.get<ApartmentDto>(`/apartments/${id}`);

    return {
      title: data.title,
      description: data.description,
    };
  } catch (error) {
    if (isAxiosError(error) && error.response?.status === 404) {
      return {
        title: "Объявления не найдено",
        description: "Generated by create next app",
      };
    }

    return {
      title: "Ошибка загрузки объявления",
      description: "Generated by create next app",
    };
  }
};

const ApartmentPage = async ({ params }: Props) => {
  const id = (await params).id;

  return (
    <Container className="mb-14">
      <SingleDataPage id={id} />
    </Container>
  );
};

export default ApartmentPage;
