import { Inter } from "next/font/google";
import type { Metadata } from "next";

import { AuthLoginModal } from "@/components/auth/Login";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/Header";
import { Banner } from "@/components/Banner";
import { Footer } from "@/components/Footer";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Next.js (App Route), Tailwind CSS, shad/cn, zustand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body className="antialiased">
        <AuthLoginModal />
        <Header />
        <Banner />
        {children}
        <Footer />
        <Toaster position="top-right" theme="light" closeButton richColors />
      </body>
    </html>
  );
}
